name: UnitTest

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Googletest 1.16.0
      run: |
        git clone -q https://github.com/google/googletest.git /tmp/googletest
        cd /tmp/googletest
        git checkout v1.16.0
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
        rm -rf /tmp/googletest

    - name: Install Benchmark 1.9.1
      run: |
        git clone -q https://github.com/google/benchmark.git /tmp/benchmark
        cd /tmp/benchmark
        git checkout v1.9.1
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON .. 
        make -j$(nproc)
        sudo make install
        rm -rf /tmp/benchmark

    - name: Test
      run: |
        ls -l /usr/local/lib
        cd optimus
        echo $(pwd)
        g++ -v
        make ts_sum_test

