name: UnitTest

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build wget tar

    - name: Install Googletest 1.16.0
      run: |
        git clone -q https://github.com/google/googletest.git
        cd googletest
        git checkout v1.16.0
        mkdir build
        cd build
        cmake .. -DBUILD_SHARED_LIBS=OFF
        make -j$(nproc)
        sudo cp -r googletest/include/* /usr/local/include/
        sudo cp libgtest.a /usr/local/lib/
        sudo cp libgtest_main.a /usr/local/lib/

    - name: Install Benchmark 1.9.1
      run: |
        git clone -q https://github.com/google/benchmark.git
        cd benchmark
        git checkout v1.9.1
        mkdir build
        cd build
        cmake .. -DBENCHMARK_ENABLE_TESTING=OFF -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBUILD_SHARED_LIBS=OFF
        make -j$(nproc)
        sudo cp include/benchmark/* /usr/local/include/benchmark/
        sudo cp libbenchmark.a /usr/local/lib/
        sudo cp libbenchmark_main.a /usr/local/lib/

    - name: Test
      run: |
        cd optimus
        echo $(pwd)
        make ts_sum_test

