name: UnitTest

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: Bacondish2023/setup-googletest@v1
      with:
        tag: v1.16.0
    # - name: Install Googletest 1.16.0
    #   run: |
    #     git clone -q https://github.com/google/googletest.git
    #     cd googletest
    #     git checkout v1.16.0
    #     mkdir build
    #     cd build
    #     cmake ..
    #     make -j$(nproc)
    #     sudo make install

    - name: Install Benchmark 1.9.1
      run: |
        git clone -q https://github.com/google/benchmark.git
        cd benchmark
        git checkout v1.9.1
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DBENCHMARK_DOWNLOAD_DEPENDENCIES=OFF .. 
        make -j$(nproc)
        sudo make install

    - name: Test
      run: |
        cd optimus
        echo $(pwd)
        make ts_sum_test

